label zetemort:
    if chap=0:
        jump zetemort0
    if chap==1:
        jump zetemort1
    if chap==2:
        jump zetemort2
    if chap==3:
        jump zetemort3
    if chap==4:
        jump zetemort4
    if chap==5:
        jump zetemort5